export const searchAreas = {
  city: [
    "Delhi",
    "New Delhi",
    "Agra",
    "Varanasi",
    "Jaipur",
    "Lucknow",
    "Chandigarh",
    "Amritsar",
    "Shimla",
    "Dehradun",
    "Jammu",
    "Srinagar",
    "Haridwar",
    "Mumbai",
    "Pune",
    "Nagpur",
    "Surat",
    "Vadodara",
    "Ahmedabad",
    "Goa",
    "Rajkot",
    "Indore",
    "Bhopal",
    "Bangalore",
    "Chennai",
    "Hyderabad",
    "Kochi",
    "Thiruvananthapuram",
    "Madurai",
    "Coimbatore",
    "Visakhapatnam",
    "Mysore",
    "Tirupati",
    "Vijayawada",
    "Bhubaneswar",
    "Kolkata",
    "Patna",
    "Ranchi",
    "Jamshedpur",
    "Durgapur",
    "Gangtok",
    "Shillong",
    "Agartala",
    "Raipur",
    "Jabalpur",
    "Gwalior",
    "Satna",
    "Imphal",
    "Aizawl",
    "Kohima",
    "Itanagar",
    "Puducherry",
    "Chandigarh",
    "Bhubaneswar",
    "Guwahati",
    "Tirunelveli",
    "Rajahmundry",
    "Rourkela",
    "Madurai",
    "Bikaner",
    "Udaipur",
    "Gorakhpur",
    "Kanpur",
    "Aligarh",
    "Meerut",
    "Faridabad",
    "Ghaziabad",
    "Noida",
    "Nashik",
    "Solapur",
    "Kolhapur",
    "Chandrapur",
    "Gwalior",
    "Raigarh",
    "Kochi",
    "Nagaland",
    "Cuttack",
    "Mangalore",
    "Vadodara",
    "Chidambaram",
    "Jammu",
    "Vellore",
    "Shivamogga",
    "Kochi",
    "Jodhpur",
    "Aurangabad",
  ],

  state: [
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chhattisgarh",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttarakhand",
    "Uttar Pradesh",
    "West Bengal",
  ],
  zone: ["North", "South", "East", "West", "Central"],
};

export const cities = [
  "Delhi",
  "New Delhi",
  "Agra",
  "Varanasi",
  "Jaipur",
  "Lucknow",
  "Chandigarh",
  "Amritsar",
  "Shimla",
  "Dehradun",
  "Jammu",
  "Srinagar",
  "Haridwar",
  "Mumbai",
  "Pune",
  "Nagpur",
  "Surat",
  "Vadodara",
  "Ahmedabad",
  "Goa",
  "Rajkot",
  "Indore",
  "Bhopal",
  "Bangalore",
  "Chennai",
  "Hyderabad",
  "Kochi",
  "Thiruvananthapuram",
  "Madurai",
  "Coimbatore",
  "Visakhapatnam",
  "Mysore",
  "Tirupati",
  "Vijayawada",
  "Bhubaneswar",
  "Kolkata",
  "Patna",
  "Ranchi",
  "Jamshedpur",
  "Durgapur",
  "Gangtok",
  "Shillong",
  "Agartala",
  "Raipur",
  "Jabalpur",
  "Gwalior",
  "Satna",
  "Imphal",
  "Aizawl",
  "Kohima",
  "Itanagar",
  "Puducherry",
  "Chandigarh",
  "Bhubaneswar",
  "Guwahati",
  "Tirunelveli",
  "Rajahmundry",
  "Rourkela",
  "Madurai",
  "Bikaner",
  "Udaipur",
  "Gorakhpur",
  "Kanpur",
  "Aligarh",
  "Meerut",
  "Faridabad",
  "Ghaziabad",
  "Noida",
  "Nashik",
  "Solapur",
  "Kolhapur",
  "Chandrapur",
  "Gwalior",
  "Raigarh",
  "Kochi",
  "Nagaland",
  "Cuttack",
  "Mangalore",
  "Vadodara",
  "Chidambaram",
  "Jammu",
  "Vellore",
  "Shivamogga",
  "Kochi",
  "Jodhpur",
  "Aurangabad",
];

export const states = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttarakhand",
  "Uttar Pradesh",
  "West Bengal",
];

export const cognizable_offenses: Array<{ offense: string, section: string }> = [
  {
    offense: "Murder",
    section: "Section 302, IPC",
  },
  {
    offense: "Rape",
    section: "Section 376, IPC",
  },
  {
    offense: "Robbery",
    section: "Section 392, IPC",
  },
  {
    offense: "Burglary",
    section: "Section 441, IPC",
  },
  {
    offense: "Kidnapping",
    section: "Section 363, IPC",
  },
  {
    offense: "Dowry Death",
    section: "Section 304B, IPC",
  },
  {
    offense: "Culpable Homicide",
    section: "Section 304, IPC",
  },
  {
    offense: "Grievous Hurt",
    section: "Section 320, IPC",
  },
  {
    offense: "Assault (Grievous Injury)",
    section: "Section 325, IPC",
  },
  {
    offense: "Extortion",
    section: "Section 383, IPC",
  },
  {
    offense: "Theft",
    section: "Section 378, IPC",
  },
  {
    offense: "Arson",
    section: "Section 435, IPC",
  },
  {
    offense: "Corruption",
    section: "Prevention of Corruption Act, 1988",
  },
  {
    offense: "Fraudulent Cheque Issuance",
    section: "Section 138, Negotiable Instruments Act",
  },
  {
    offense: "Human Trafficking",
    section: "Various provisions under IPC and special laws",
  },
  {
    offense: "Unlawful Assembly",
    section: "Section 141, IPC",
  },
  {
    offense: "Criminal Breach of Trust",
    section: "Section 406, IPC",
  },
  {
    offense: "Cheating",
    section: "Section 420, IPC",
  },
];


export const LicenseTypes = [
  "Firearm",
  "Driving",
  "Liquor",
  "Private_Security",
  "Event_Entertainment",
  "Pet",
  "Import_Export",
  "Knife_Blade",
  "Protest",
  "Hunting",
  "Restricted_Area"
]